// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final_PrograIV.FinalProjectDataBase;

#nullable disable

namespace Proyecto_Final_PrograIV.Migrations
{
    [DbContext(typeof(FinalProjectDbContext))]
    [Migration("20260603162358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.CandidateOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("OfferId");

                    b.ToTable("CandidateOffers");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.CandidateSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Email = "contact@innowise.com",
                            Name = "Innowise",
                            Password = "1234",
                            WebSite = "https://innowise.com/es/tecnologias/desarrollo-dot-net/"
                        },
                        new
                        {
                            CompanyId = 2,
                            Email = "contact@turing.com",
                            Name = "TURING",
                            Password = "123",
                            WebSite = "https://www.turing.com/es/jobs/remote-react-js-developer"
                        },
                        new
                        {
                            CompanyId = 3,
                            Email = "info@paralleldevs.com",
                            Name = "Parallel Devs",
                            Password = "12345",
                            WebSite = "https://www.paralleldevs.com/"
                        });
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            OfferId = 1,
                            CompanyId = 2,
                            Description = "Revisión",
                            Job = "QA"
                        },
                        new
                        {
                            OfferId = 2,
                            CompanyId = 1,
                            Description = "Desarrollar sistemas",
                            Job = "Desarrollo web"
                        },
                        new
                        {
                            OfferId = 3,
                            CompanyId = 2,
                            Description = "Servicios API",
                            Job = "Programador backend"
                        },
                        new
                        {
                            OfferId = 4,
                            CompanyId = 3,
                            Description = "Administrar proyectos TI",
                            Job = "Gerente IT"
                        },
                        new
                        {
                            OfferId = 5,
                            CompanyId = 1,
                            Description = "Interfaces modernas",
                            Job = "Frontend Developer"
                        },
                        new
                        {
                            OfferId = 6,
                            CompanyId = 2,
                            Description = "Pipelines y despliegues",
                            Job = "DevOps Engineer"
                        },
                        new
                        {
                            OfferId = 7,
                            CompanyId = 3,
                            Description = "Gestión de bases de datos",
                            Job = "Administrador de BD"
                        },
                        new
                        {
                            OfferId = 8,
                            CompanyId = 1,
                            Description = "Apps móviles con React Native",
                            Job = "Mobile Developer"
                        },
                        new
                        {
                            OfferId = 9,
                            CompanyId = 2,
                            Description = "Frontend y Backend",
                            Job = "Fullstack Developer"
                        },
                        new
                        {
                            OfferId = 10,
                            CompanyId = 3,
                            Description = "Atención a usuarios",
                            Job = "Soporte Técnico"
                        });
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.OfferSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("SkillId");

                    b.ToTable("OfferSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OfferId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 2,
                            OfferId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 3,
                            OfferId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 4,
                            OfferId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 5,
                            OfferId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 6,
                            OfferId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 7,
                            OfferId = 3,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 8,
                            OfferId = 3,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 9,
                            OfferId = 4,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 10,
                            OfferId = 4,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 11,
                            OfferId = 5,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 12,
                            OfferId = 5,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 13,
                            OfferId = 5,
                            SkillId = 11
                        },
                        new
                        {
                            Id = 14,
                            OfferId = 6,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 15,
                            OfferId = 6,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 16,
                            OfferId = 6,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 17,
                            OfferId = 7,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 18,
                            OfferId = 7,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 19,
                            OfferId = 8,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 20,
                            OfferId = 8,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 21,
                            OfferId = 8,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 22,
                            OfferId = 9,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 23,
                            OfferId = 9,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 24,
                            OfferId = 9,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 25,
                            OfferId = 10,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 26,
                            OfferId = 10,
                            SkillId = 13
                        });
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Icon = "https://www.svgrepo.com/show/452184/csharp.svg",
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = 2,
                            Icon = "https://www.svgrepo.com/show/331761/sql-database-sql-azure.svg",
                            Name = "SQL"
                        },
                        new
                        {
                            SkillId = 3,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/a/a8/NestJS.svg",
                            Name = "Nest"
                        },
                        new
                        {
                            SkillId = 4,
                            Icon = "https://www.svgrepo.com/show/354099/mysql.svg",
                            Name = "MySQL"
                        },
                        new
                        {
                            SkillId = 5,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = 6,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg",
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = 7,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
                            Name = "React"
                        },
                        new
                        {
                            SkillId = 8,
                            Icon = "https://www.svgrepo.com/show/452075/node-js.svg",
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = 9,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = 10,
                            Icon = "https://www.svgrepo.com/show/452228/html-5.svg",
                            Name = "HTML"
                        },
                        new
                        {
                            SkillId = 11,
                            Icon = "https://www.svgrepo.com/show/452185/css-3.svg",
                            Name = "CSS"
                        },
                        new
                        {
                            SkillId = 12,
                            Icon = "https://www.svgrepo.com/show/354926/docker.svg",
                            Name = "Docker"
                        },
                        new
                        {
                            SkillId = 13,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/3/3f/Git_icon.svg",
                            Name = "Git"
                        },
                        new
                        {
                            SkillId = 14,
                            Icon = "https://upload.wikimedia.org/wikipedia/commons/f/fa/Microsoft_Azure.svg",
                            Name = "Azure"
                        });
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.CandidateOffer", b =>
                {
                    b.HasOne("Proyecto_Final_PrograIV.Entities.Candidate", "Candidate")
                        .WithMany("CandidateOffers")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Final_PrograIV.Entities.Offer", "Offer")
                        .WithMany("CandidateOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.CandidateSkill", b =>
                {
                    b.HasOne("Proyecto_Final_PrograIV.Entities.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Final_PrograIV.Entities.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Offer", b =>
                {
                    b.HasOne("Proyecto_Final_PrograIV.Entities.Company", "Company")
                        .WithMany("Offers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.OfferSkill", b =>
                {
                    b.HasOne("Proyecto_Final_PrograIV.Entities.Offer", "Offer")
                        .WithMany("OfferSkills")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Final_PrograIV.Entities.Skill", "Skill")
                        .WithMany("OfferSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Candidate", b =>
                {
                    b.Navigation("CandidateOffers");

                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Company", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Offer", b =>
                {
                    b.Navigation("CandidateOffers");

                    b.Navigation("OfferSkills");
                });

            modelBuilder.Entity("Proyecto_Final_PrograIV.Entities.Skill", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("OfferSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
